apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "odm.dbserver.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ template "odm.dbserver.fullname" . }}
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: {{ template "fullname" . }}-volume
        persistentVolumeClaim:
          claimName: {{ template "odm.persistenceclaim.fullname" . }}
      {{- end }}
      containers:
      - name: {{ template "odm.dbserver.fullname" . }}
        image: {{ .Values.image.repository }}/dbserver:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.persistence.postgresql.user }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.persistence.postgresql.password }}"
        - name: POSTGRES_DB
          value:  "{{ .Values.persistence.postgresql.databasename }}"
        - name: PGDATA
          value:  "/pgdata"
        - name: SAMPLE
          value: "{{ .Values.persistence.populateDataSample }}"
        ports:
        - containerPort: 5432
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: {{ template "fullname" . }}-volume
            mountPath: /pgdata
        {{- end }}
        {{- if (not (empty .Values.image.pullSecrets )) }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
         {{- end }}
