###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "odm.decisionrunner.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.decisionRunner.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ template "odm.decisionrunner.fullname" . }}
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "odm.decisionrunner.fullname" . }}
        image: {{ .Values.image.repository}}/{{ .Values.image.prefix }}-decisionrunner:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: "DBSERVER_NAME"
            value: {{ template "odm.dbserver.fullname" . }}
        ports:
        - containerPort: 9070
    {{- if (not (empty .Values.image.pullSecrets )) }}
      imagePullSecrets:
        -name: {{ .Values.image.pullSecrets }}
    {{- end }}
