apiVersion: v1
kind: Service
metadata:
  name: {{ template "odm.decisionserverruntime.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    run: {{ template "odm.decisionserverruntime.fullname" . }}
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
   - protocol: TCP
     port: 9080
