apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "odm.decisionserverruntime.fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.decisionServerRuntime.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ template "odm.decisionserverruntime.fullname" . }}
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "odm.decisionserverruntime.fullname" . }}
        image: {{ .Values.image.repository}}/{{ .Values.image.prefix }}-decisionserverruntime:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: "DBSERVER_NAME"
            value: {{ template "odm.dbserver.fullname" . }}
          - name: "DECISIONSERVERCONSOLE_NAME"
            value: {{ template "odm.decisionserverconsole.fullname" . }}
        ports:
        - containerPort: 9080
        {{- if (not (empty .Values.image.pullSecrets )) }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
         {{- end }}
