# Default values for odmcharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: mycluster:8500/odmdocker
  tag: 8.9.0
  pullPolicy: IfNotPresent

service:
  type: NodePort


decisionServerRuntime:
  replicaCount: 2

decisionCenter:
  replicaCount: 1

decisionRunner:
  replicaCount: 1

