# Default values for odmcharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ibmcom
  prefix: odm
  tag: 8.9.0
  pullPolicy: IfNotPresent
## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
##  - name: admin.registrykey
  pullSecrets:

persistence:
  enabled: true


service:
  type: NodePort

decisionServerRuntime:
  replicaCount: 2

decisionCenter:
  replicaCount: 1

decisionRunner:
  replicaCount: 1
