# A Hostpath persistence volume for development and testing on a single-node cluster
# It uses a file or directory on the Node to emulate network-attached storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odmpv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/odm"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odmclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: dbserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: dbserver
    spec:
      volumes:
      - name: odm-volume
        persistentVolumeClaim:
          claimName: odmclaim
      containers:
      - name: dbserver
        image: odmdocker/dbserver:8.9.0
        env:
        # recreate the database with a sample ruleapp when set to true
        - name: SAMPLE
          value: "true"
        ports:
        - containerPort: 1527
        volumeMounts:
          - name: odm-volume
            # mount path within the container
            mountPath: /dbs
---
apiVersion: v1
kind: Service
metadata:
  name: dbserver
  labels:
    run: dbserver
spec:
  selector:
    run: dbserver
  type: NodePort
  ports:
   - protocol: TCP
     port: 1527
---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: decisionserverconsole
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: decisionserverconsole
    spec:
      containers:
      - name: decisionserverconsole
        image: odmdocker/decisionserverconsole:8.9.0
        ports:
        - containerPort: 9080
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: decisionserverconsole
  labels:
    name: decisionserverconsole
spec:
  selector:
    run: decisionserverconsole
  type: NodePort
  ports:
   - protocol: TCP
     port: 9080
---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: decisionserverruntime
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: decisionserverruntime
    spec:
      containers:
      - name: decisionserverruntime
        image: odmdocker/decisionserverruntime:8.9.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: decisionserverruntime
  labels:
    run: decisionserverruntime
spec:
  selector:
    run: decisionserverruntime
  type: NodePort
  ports:
   - protocol: TCP
     port: 9080
---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: decisioncenter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: decisioncenter
    spec:
      containers:
      - name: decisioncenter
        image: odmdocker/decisioncenter:8.9.0
        env:
        - name: SAMPLE
        ports:
        - containerPort: 9060
---
apiVersion: v1
kind: Service
metadata:
  name: decisioncenter
  labels:
    run: decisioncenter
spec:
  selector:
    run: decisioncenter
  type: NodePort
  ports:
   - protocol: TCP
     port: 9060
---
apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: decisionrunner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: decisionrunner
    spec:
      containers:
      - name: decisionrunner
        image: odmdocker/decisionrunner:8.9.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: decisionrunner
  labels:
    run: decisionrunner
spec:
  selector:
    run: decisionrunner
  type: NodePort
  ports:
   - protocol: TCP
     port: 9080
