apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: odm-decisionserverruntime
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: odm-decisionserverruntime
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: odm-decisionserverruntime
        image: {{ .Values.image.repository}}/decisionserverruntime:{{ .Values.image.tag }}
        ports:
        - containerPort: 9080