###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2017. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
#
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: odm-decisioncenter
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.decisionCenter.replicaCount }}
  template:
    metadata:
      labels:
        run: odm-decisioncenter
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: odm-decisioncenter
        image: {{ .Values.image.repository}}/decisioncenter:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9060
      imagePullSecrets:
      - name: admin.registrykey